[phases.setup]
nixPkgs = ['python39', 'ffmpeg']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['chmod +x railway-start.py']

[start]
cmd = 'gunicorn flask_app:app --bind 0.0.0.0:$PORT'